### ISSUE TITLE
working example for aliasing multiple versions of a package

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#174]
Is something like this possible yet?

```
dependencies:
  dappsys: 0.1.1
  dappsys_0_1_0:
    name: dappsys
    version: 0.1.0
```
