### ISSUE TITLE
MakerUserMockRegistry integration on devchain

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#203]
I am trying to integrate `maker-otc` with `makeruser` (`MakerUserMockRegistry` specifically) and get both deployed on a private devchain. In order to do so I have created a `deploy.ds`:
```
import makeruser
var mock_registry = new MakerUserMockRegistry()
var otc = new AtomicTrade(mock_registry)
export mock_registry
export otc
```

My `dappfile` is the default one from `maker-otc`:
```
name: maker-otc
version: 0.1.0
layout:
  sol_sources: contracts
  build_dir: build
dependencies:
  makeruser: 0.1.0
  dappsys: 1.0.1
```

Even though `makeruser` is configured as dependency, `dapple` complains that it isn't declared:
```
  ERROR: makeruser is not declared in dappfile environment!
```

Possibly this is the wrong approach, but how would I go about having both the `MakerUserMockRegistry` and `maker-otc` dapps deployed as part of the same deployment process on the same devchain?
