### ISSUE TITLE
dapple libraries design issues

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#212]
Since delegatecall is now available libraries should become First-class citizen of packages.
Here we should discuss on how dapple treats libraries
A few thoughts:

## dappfile - analog to objects:
```
environments:
  morden:
    objects:
      auth_factory1:
        class: DSAuthFactory
        address: '0x7639a37b8ecbd68e15b8e173897c6c0dea462452'
    libraries:
      Math:  // <- this name is unnecessary
        class: Math
        address: '0x0123456789012345678901234567890123456789'
```
## search
* addresses of libraries are searched recursively beginning from the current dappfile through every dependency (Level-order)
* a warning can be thrown if several different libraries with the same class name are found in one level.

## test
* libraries must be present (imported) and gets redeployed and linked on every test

## build
* if no library is found, code is build with solc native __Library___  substitution

## run
Library `Math` and `String` can be deployed:
```
...
new Math(); // internally Math: 0x1234
// or
var math = new Math() // note here that a new Math contract is NOT deployed but the address of the know is returned
var c1 = MathUser() // a contract which uses math is deployed, no address needs to get passed
var c2 = StringUser() // throws an error, because String library is not deployed or found yet.
```

Thoughts? Did I miss something?
