### ISSUE TITLE
dapplescript type system

### ISSUE THREAD

**Issue by mhhf** [nexusdev/dapple#227]
Addressing [this issue](https://github.com/MakerDAO/maker-user/issues/6) #173 #212 and some others, we should thing about dapples type system. First I want to propose refactoring the dappfile to allow arbitrary types in an environment by assigning a type value to each entry:

Before:
```
environments:
  morden:
    objects:
      auth_factory1:
        class: DSAuthFactory
        address: '0x7639a37b8ecbd68e15b8e173897c6c0dea462452'
```

After:
```
environments:
  morden:
      auth_factory1:
        type: DSAuthFactory
        value: '0x7639a37b8ecbd68e15b8e173897c6c0dea462452'
      someaddress:
        type: Address
        value: '0xca4c8055eff501d466a4d1bf5148c623c5eaf5dc'
     somestring:
        type: String
        value: '0x1be9a61d65db97d8d6a457e55bf6baf00b32c517'
```

Objects, libraries, strings, numbers, etc. are all covered with this approach. Do we need complex types like Lists, Objects, etc?

## Casting
Explicite type casting:
```
var mock_registry = new MakerUserMockRegistry()
var mkr_frontend = DSToken(mock_registry.get('MKR'))
export mkr_frontend
```

Implicite type casting:
```
DSToken mkr_frontend = mock_registry.get('MKR')
```

Should we allow both?
