### ISSUE TITLE
dapple migrate - not helpful when missing dapplerc [usability]

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/dapple#327]
```
~/ds-auth# dapple migrate
cannot find dapplerc, aborting!
```

`dapple init` in a fresh dir doesn't set up dapplerc either. What do I do?

**Comment by mhhf** [comment]
take this generic: ~/.dapplerc:
```
environments:
  default:
    ethereum: internal
  evm: default
```
