### ISSUE TITLE
Dappfile vs dappfile inconsistencies

### ISSUE THREAD

**Issue by nanexcool** [nexusdev/dapple#373]
Tested on Ubuntu 16 with Dapple 0.8.36.

`dapple init` creates a Dappfile (capital D).

```
version: 0.0.1-dev
tags: []
layout:
  sol_sources: src
  build_dir: build
  packages_directory: .dapple/packages/
dependencies: {}
ignore: []
name: token-faucet
```

`dapple chain new` then creates a new dappfile (lowercase d) with the added environment info:

```
version: 0.0.1-dev
tags: []
layout:
  sol_sources: src
  build_dir: build
  packages_directory: .dapple/packages/
dependencies: {}
ignore: []
name: token-faucet
dapple_version: 0.8.36
environments:
  develop:
    objects: {}
    type: TestRPC
```

Previous Dappfile is unchanged.
